[tool.poetry]
<<<<<<< HEAD
package-mode = false

=======
>>>>>>> 50b771605cb5795d774bc8d6a2d3eab6a69a5949
name = "ecommerce"
version = "0.1.0"
description = "Projeto de automação de testes"
authors = ["PabloJAndrade <pcraveirodeandrade@gmail.com>"]
readme = "README.md"
packages = [{ include = "resource" }, { include = "test" }]

[tool.poetry.dependencies]
python = ">=3.12"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
